language: php

dist: trusty

cache:
  directories:
    - $HOME/.composer/cache/files

php:
  - 5.6
  - 7.0
  - 7.1
  - nightly
  - hhvm

env:
  - 'COMPOSER_FLAGS="--prefer-stable --prefer-lowest"'
  - 'COMPOSER_FLAGS=""'

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly
  fast_finish: true

install:
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction --prefer-dist

script:
  - vendor/bin/phpcs -p --warning-severity=0 src/ tests/
  - vendor/bin/phpunit tests/

after_script:
  - test -f ./tests/report/coverage.clover && (wget https://scrutinizer-ci.com/ocular.phar; php ocular.phar code-coverage:upload --format=php-clover ./tests/report/coverage.clover)
